---
- name: Update and upgrade apt packages
  ansible.builtin.apt:
    upgrade: full
    update_cache: true
    cache_valid_time: 86400
    autoclean: true
    autoremove: true

# Install software
- name: Install packages
  ansible.builtin.apt:
    name:
      - "{{ item }}"
    state: present
    update_cache: true
    cache_valid_time: 86400
  when: ansible_os_family == 'Debian'
  with_items:
    - "{{ packages_present_debian }}"

# Remove unused software, open only required ports.
- name: Remove unused packages.
  ansible.builtin.package:
    name:
      - "{{ item }}"
    state: absent
  with_items:
    - "{{ packages_absent_debian }}"

- name: Copy unattended-upgrades configuration files in place.
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/etc/apt/apt.conf.d/{{ item }}"
    owner: root
    group: root
    mode: "0644"
  with_items:
    - 20auto-upgrades
    - 50unattended-upgrades
  when: ansible_os_family == 'Debian'
